### ISSUE TITLE
More CodeLouisville Courses to be Completed

### ISSUE THREAD

**Issue by sue-f** [sue-f/treehouse-github#2]
## TODO

*Some of the courses left to complete the CodeLouisville Front End Web Dev track*

* [ ] CSS Layout Basics
* [ ] JavaScript Loops, Arrays and Objects
* [ ] CSS Selectors
* [ ] JavaScript and the DOM
* [ ] Responsive Layouts
* [ ] jQuery Basics

:bowtie:  😲 

cc @sue-f
